# k8s-web-app/09-api-service.yaml
# API Service = キッチンの内線電話（ClusterIP：フロントエンドからの内部通信用）

apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: k8s-web-app
spec:
  type: ClusterIP               # 外部公開不要（Frontend の nginx が proxy_pass http://api-svc/ で到達）
  selector:
    app: api                    # ↔ Deployment(api) の labels.app: api にマッチ → 2台にロードバランス
  ports:
    - port: 80                  # Service:80 → Pod:80
      targetPort: 80
